library(shiny)
library(magrittr)
library(shinyWidgets)
library(promises)
library(future)
library(shinycssloaders)

require(companyDataScrapeR)
require(fdoR)
require(dateR)
require(assertR)
require(excelsioR)
require(fileR)
require(wgbDataScrapeR)
require(webScrapeR)

plan(multisession)

source("../R/plot_functions.R")
source("../R/table_functions.R")